 [scenario]
name = "test_mabm"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
verbose = true

[inputs]
events = "./fixtures/fixtures_1perc/output_events.xml.gz"
network = "./fixtures/fixtures_1perc/output_network.xml.gz"
transit_schedule = "./fixtures/fixtures_1perc/output_transitSchedule.xml.gz"
transit_vehicles = "./fixtures/fixtures_1perc/output_transitVehicles.xml.gz"
attributes = "./fixtures/fixtures_1perc/population_attributes.xml"
plans = "./fixtures/fixtures_1perc/output_plans.xml.gz"

[event_handlers]
volume_counts = ["car"]
passenger_counts = ["bus", "train"]
stop_interactions = ["bus", "train"]

[plan_handlers]
mode_share = ["all"]

[outputs]
path = "./outputs/outputs_01perc"
contract = true
post_processing = ["vkt"]

[benchmarking]
benchmarks = ["london_inner_cordon_car"]
