[scenario]
name = "test_town"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
verbose = false
version = 11

[inputs]
events = "./tests/test_fixtures/output_events.xml"
network = "./tests/test_fixtures/output_network.xml"
transit_schedule = "./tests/test_fixtures/output_transitSchedule.xml"
transit_vehicles = "./tests/test_fixtures/output_transitVehicles.xml"
attributes = "./tests/test_fixtures/output_personAttributes.xml"
plans= "./tests/test_fixtures/output_plans.xml"
output_config_path = "./tests/test_fixtures/output_config.xml"

[outputs]
path = "./outputs"

[event_handlers]
link_vehicle_counts = ["car", "bus"]
link_passenger_counts = ["bus"]
stop_passenger_counts = ["bus"]
stop_passenger_waiting = ["all"]

[plan_handlers]
mode_shares = ["all"]
trip_logs = ["all"]
agent_highway_distance_logs = ["car"]
trip_highway_distance_logs = ["car"]

[post_processors]
vkt = ["car"]
plan_summary = ["all"]
trip_duration_breakdown = ["all"]
trip_euclid_distance_breakdown = ["all"]

[benchmarks]
test_pt_interaction_counter = ["bus"]
test_link_cordon = ["car"]
#test_duration_comparison = ["all"]
test_euclidean_distance_comparison = ["all"]
duration_comparison = {mode = ["all"], benchmark_data_path = "./tests/test_outputs/trip_duration_breakdown_all.csv"}
