[scenario]
name = "test_town"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
verbose = false

[inputs]
events = "./tests/test_fixtures/output_events.xml"
network = "./tests/test_fixtures/output_network.xml"
transit_schedule = "./tests/test_fixtures/output_transitSchedule.xml"
transit_vehicles = "./tests/test_fixtures/output_transitVehicles.xml"
attributes = "./tests/test_fixtures/output_personAttributes.xml"
plans= "./tests/test_fixtures/output_plans.xml"
output_config_path = "./tests/test_fixtures/output_config.xml"

[outputs]
path = "./outputs"
contract = false

[event_handlers]
volume_counts = ["car", "bus"]
passenger_counts = ["bus"]
stop_interactions = ["bus"]
waiting_times = ["all"]

[plan_handlers]
mode_share = ["all"]
trip_logs = ["all"]
agent_highway_distances = ["car"]
trip_highway_distances = ["car"]

[post_processors]
vkt = ["car"]
plan_summary = ["all"]
trip_logs = ["all"]
trip_breakdowns = ["all"]

[benchmarks]
test_pt_interaction_counter = ["bus"]
test_link_cordon = ["car"]
test_duration_comparison = ["all"]
test_euclidean_distance_comparison = ["all"]