 [scenario]
name = "ireland"
time_periods = 24
scale_factor = 0.01
crs = "EPSG:27700"
verbose = true

[inputs]
events = "./fixtures/fixtures_ireland_test_100/output_events.xml.gz"
network = "./fixtures/fixtures_ireland_test_100/output_network.xml.gz"
transit_schedule = "./fixtures/fixtures_ireland_test_100/output_transitSchedule.xml.gz"
transit_vehicles = "./fixtures/fixtures_ireland_test_100/output_transitVehicles.xml.gz"
attributes = "./fixtures/fixtures_ireland_test_100/output_personAttributes.xml.gz"
plans = "./fixtures/fixtures_ireland_test_100/output_plans.xml.gz"

[outputs]
path = "./outputs/ireland/test_100/"
contract = true
post_processing = []

[event_handlers]
volume_counts = ["car"]
passenger_counts = ["bus", "train", "tram", "ferry"]
stop_interactions = ["bus", "train", "tram", "ferry"]

[plan_handlers]
mode_share = ["all"]

[benchmarking]
benchmarks = ["dublin_canal_cordon_car", "ireland_commuter_modeshare"]

