[scenario]
name = "test_scenario"
time_periods = 24
scale_factor = 0.01
crs = "EPSG:27700"

[inputs]
events = "./fixtures/output_events.xml"
network = "./fixtures/output_network.xml"
transit_schedule = "./fixtures/output_transitSchedule.xml"
transit_vehicles = "./fixtures/output_transitVehicles.xml"

[outputs]
path = "./outputs"
contract = true

[handlers]
volume_counts = ["car"]
passenger_counts = ["bus", "train"]