[scenario]
name = "test"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
verbose = true

[inputs]
events = "./fixtures/fixtures_01perc/baseline/output_events.xml.gz"
network = "./fixtures/fixtures_01perc/baseline/output_network.xml.gz"
transit_schedule = "./fixtures/fixtures_01perc/baseline/output_transitSchedule.xml.gz"
transit_vehicles = "./fixtures/fixtures_01perc/baseline/output_transitVehicles.xml.gz"
attributes = "./fixtures/fixtures_01perc/baseline/output_personAttributes.xml.gz"
plans = "./fixtures/fixtures_01perc/baseline/output_plans.xml.gz"

[outputs]
path = "./outputs/testing_elara_outputs"
contract = true

[event_handlers]
volume_counts = ["car"]
passenger_counts = ["bus", "train"]
stop_interactions = ["bus", "train"]

[plan_handlers]
mode_share = ["all"]

[post_processors]
vkt = ["car"]

[benchmarks]
london_inner_cordon_car = ["car"]
