 [scenario]
name = "test_town"
time_periods = 24
scale_factor = 1
crs = "EPSG:27700"
verbose = true

[inputs]
events = "./fixtures/fixtures_tests/output_events.xml.gz"
network = "./fixtures/fixtures_tests/output_network.xml.gz"
transit_schedule = "./fixtures/fixtures_tests/output_transitSchedule.xml.gz"
transit_vehicles = "./fixtures/fixtures_tests/output_transitVehicles.xml.gz"
attributes = "./fixtures/fixtures_tests/output_personAttributes.xml.gz"
plans = "./fixtures/fixtures_tests/output_plans.xml.gz"

[event_handlers]
volume_counts = ["car", "bus"]
passenger_counts = ["bus"]
stop_interactions = ["bus"]

[plan_handlers]
mode_share = ["all"]

[outputs]
path = "./outputs/test_town"
contract = true
post_processing = ["vkt"]

[benchmarking]
benchmarks = ["test_town_cordon", "test_town_peak_cordon", "test_town_modeshare"]
