[scenario]
name = "test_town"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
debug = false
using_experienced_plans = false

[inputs]
events = "./tests/test_fixtures/output_events.xml"
network = "./tests/test_fixtures/output_network.xml"
transit_schedule = "./tests/test_fixtures/output_transitSchedule.xml"
transit_vehicles = "./tests/test_fixtures/output_transitVehicles.xml"
plans = "./tests/test_fixtures/output_plans_v12.xml"
output_config_path = "./tests/test_fixtures/output_config.xml"
vehicles = "./tests/test_fixtures/output_vehicles.xml.gz"

[outputs]
path = "./outputs"

[plan_handlers]
trip_modes = {name="Census", groupby_person_attributes=["age", "subpopulation"]}

