[scenario]
name = "test_town"
time_periods = 24
scale_factor = 0.0001
crs = "EPSG:27700"
verbose = false
version = 12
using_experienced_plans = false

[inputs]
inputs_directory = "./tests/test_fixtures"

[outputs]
path = "./outputs"

[event_handlers]
link_vehicle_counts = ["car", "bus"]
stop_passenger_counts = ["bus"]
stop_passenger_waiting = ["all"]
link_passenger_counts = ["bus"]
vehicle_departure_log = ["bus"]
vehicle_passenger_log = ["bus"]
stop_to_stop_passenger_counts = ["bus"]
vehicle_stop_to_stop_passenger_counts = ["bus"]

[plan_handlers]
mode_shares = {attributes=["age"]}
trip_logs = ["all"]
agent_highway_distance_logs = ["car"]
trip_highway_distance_logs = ["car"]

[post_processors]
plan_summary = ["all"]
vkt = ["car"]
trip_duration_breakdown = ["all"]
trip_euclid_distance_breakdown = ["all"]

[benchmarks]
test_pt_interaction_counter = ["bus"]
test_link_cordon = ["car"]
test_duration_comparison = ["all"]
test_euclidean_distance_comparison = {modes=["all"]}
duration_comparison = {modes = ["all"], benchmark_data_path = "./tests/test_outputs/trip_duration_breakdown_all.csv"}
